### ISSUE TITLE
Community?

### ISSUE THREAD

**Issue by lolmaus** [ash-framework/core#9]
This project needs a chatroom!

Slack is the most common choice, but:
* no Markdown support
* no syntax highlighting in code blocks (unless posting a file)
* messages disappear after a short while on the free plan, and their paid plan is beyond reason for open source projects
* requires a separate username/password pair for each community

So I suggest using [Gitter](https://gitter.im).

Gitter cros:
* full Markdown support
* proper syntax highlighting
* closely integrated with GitHub, allows creating rooms tied to repos as well as custom rooms
* global auth via GitHub
* don't have to open multiple tabs to be present at unrelated chatrooms
* public rooms, no need for a custom webapp for self-invitations (private rooms also possible)
* unlimited free plan, except for private rooms maybe

Gitter cons:
* no custom emoji ![image](https://cloud.githubusercontent.com/assets/200884/24246195/4178c470-0fd7-11e7-98b4-708f0f7eb6ef.png)
* less features than Slack
* mobile apps aren't that good

**Comment by digitalsadhu** [comment]
Hey @lolmaus 
Thanks for the issue!

Good point about needing a chatroom!

I think you may be right about gitter being a better technical solution but I spend all my time in slack. I think if its in slack, i'll see it, if its in gitter, I'm going to miss messages or be slower to reply. That seems important yea? You ok if we go with slack?

**Comment by lolmaus** [comment]
Well, you did miss my message in Slack though. :P I wrote to you in Ember Slack two days before starting this issue.

That's because Slack isn't a global system. It requires having a separate tab open for every community.

As a leader of the Ash community, you'll have to commit to having the chatroom open all the time or at least regularly. That's equally true about Slack and Gitter. Being online at other Slack communities doesn't help you in any way with maintaining your presence in the Ash chatroom.

Note that Gitter is a global system: it lets you attend any number of communities from one browser tab / app instance.

Also, Gitter sets up instantaneously: you just log into Gitter with GitHub, select the Ash org and you have your public chatroom. With Slack, you'll have to have a Heroku app to let users invite themselves and another app to log messages so that they don't disappear forever.

1-on-1 messages in Slack will disappear anyway, there's nothing you can do about it:

> ![image](https://cloud.githubusercontent.com/assets/200884/24247445/ca530954-0fdc-11e7-95b2-50b46547ece8.png)

That's frustrating, by the way. People continue a discussion with you and you can't recall who they are and what they are talking about. As a community leader, you'll have that a lot. :trollface: 

***

That said, you da boss. I gave you all my argumentation, you make the choice. I will not object against it. :beers:

**Comment by digitalsadhu** [comment]
Touché!

So yea, you've convinced me damn it! Lets go with gitter then. I've had issues keeping up with gitter in the past but i'll just have to make sure I have the app front and center on my phone and such.

**Comment by lolmaus** [comment]
https://gitter.im/ash-framework/community
